#!/usr/bin/env python3
"""
Test script for DOCX to PDF converters

This script creates a sample .docx file and tests both conversion methods.
"""

import sys
import subprocess
from pathlib import Path


def create_sample_docx():
    """Create a sample .docx file for testing"""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        print("ERROR: python-docx library not found!")
        print("\nTo create sample files, install it with:")
        print("  pip install python-docx")
        print("\nOr you can test with your own .docx files instead.")
        return None
    
    print("Creating sample test document...")
    
    # Create document
    doc = Document()
    
    # Add title
    title = doc.add_heading('DOCX to PDF Converter Test', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add introduction
    intro = doc.add_paragraph()
    intro.add_run('This is a test document to verify PDF conversion preserves formatting.\n\n')
    intro.add_run('Date: ').bold = True
    intro.add_run('February 6, 2026')
    
    # Add heading
    doc.add_heading('1. Text Formatting', level=1)
    
    # Add formatted text
    p = doc.add_paragraph()
    p.add_run('This paragraph demonstrates ').add_run('bold').bold = True
    p.add_run(', ').add_run('italic').italic = True
    p.add_run(', and ').add_run('underline').underline = True
    p.add_run(' formatting.')
    
    # Add colored text
    p2 = doc.add_paragraph('This text is colored: ')
    run = p2.add_run('RED')
    run.font.color.rgb = RGBColor(255, 0, 0)
    run.bold = True
    
    # Add different font sizes
    doc.add_heading('2. Font Sizes', level=1)
    for size in [10, 12, 14, 16, 18]:
        p = doc.add_paragraph(f'This is {size}pt text')
        p.runs[0].font.size = Pt(size)
    
    # Add lists
    doc.add_heading('3. Lists', level=1)
    doc.add_paragraph('Bulleted list:', style='List Bullet')
    doc.add_paragraph('First item', style='List Bullet')
    doc.add_paragraph('Second item', style='List Bullet')
    doc.add_paragraph('Third item', style='List Bullet')
    
    doc.add_paragraph('Numbered list:', style='List Number')
    doc.add_paragraph('First step', style='List Number')
    doc.add_paragraph('Second step', style='List Number')
    doc.add_paragraph('Third step', style='List Number')
    
    # Add table
    doc.add_heading('4. Table', level=1)
    table = doc.add_table(rows=4, cols=3)
    table.style = 'Light Grid Accent 1'
    
    # Header row
    header_cells = table.rows[0].cells
    header_cells[0].text = 'Item'
    header_cells[1].text = 'Quantity'
    header_cells[2].text = 'Price'
    
    # Data rows
    data = [
        ('Apples', '10', '$5.00'),
        ('Bananas', '5', '$3.00'),
        ('Oranges', '8', '$6.00')
    ]
    
    for i, (item, qty, price) in enumerate(data, start=1):
        cells = table.rows[i].cells
        cells[0].text = item
        cells[1].text = qty
        cells[2].text = price
    
    # Add page break
    doc.add_page_break()
    
    # Add second page
    doc.add_heading('5. Multiple Pages', level=1)
    doc.add_paragraph(
        'This is on the second page to test multi-page conversion. '
        'PDF conversion should preserve page breaks and formatting across all pages.'
    )
    
    # Add footer note
    doc.add_paragraph()
    footer = doc.add_paragraph('Generated by docx_to_pdf test script')
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].italic = True
    
    # Save document
    output_file = Path('test_document.docx')
    doc.save(str(output_file))
    
    print(f"✓ Created sample document: {output_file}")
    return output_file


def test_converter(converter_script, docx_file):
    """Test a converter script"""
    print(f"\n{'='*60}")
    print(f"Testing: {converter_script}")
    print('='*60)
    
    if not Path(converter_script).exists():
        print(f"ERROR: Script not found: {converter_script}")
        return False
    
    # Run conversion
    try:
        result = subprocess.run(
            [sys.executable, converter_script, str(docx_file)],
            capture_output=True,
            text=True,
            timeout=60
        )
        
        print(result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)
        
        if result.returncode == 0:
            print(f"✓ Conversion successful!")
            return True
        else:
            print(f"✗ Conversion failed (exit code: {result.returncode})")
            return False
            
    except subprocess.TimeoutExpired:
        print("✗ Conversion timed out!")
        return False
    except Exception as e:
        print(f"✗ Error running converter: {e}")
        return False


def main():
    print("DOCX to PDF Converter Test Suite")
    print("="*60)
    
    # Check if test file exists or create it
    test_file = Path('test_document.docx')
    
    if test_file.exists():
        print(f"Using existing test file: {test_file}")
    else:
        test_file = create_sample_docx()
        if not test_file:
            print("\nNo test file available. Please:")
            print("1. Install python-docx: pip install python-docx")
            print("2. Or provide your own .docx file and run:")
            print("   python docx_to_pdf.py your_file.docx")
            sys.exit(1)
    
    # Test primary converter
    result1 = test_converter('docx_to_pdf.py', test_file)
    
    # Test simple converter if docx2pdf is available
    try:
        import docx2pdf
        result2 = test_converter('simple_docx_to_pdf.py', test_file)
    except ImportError:
        print("\n" + "="*60)
        print("Skipping simple_docx_to_pdf.py test (docx2pdf not installed)")
        print("To test it: pip install docx2pdf")
        print("="*60)
        result2 = None
    
    # Summary
    print("\n" + "="*60)
    print("TEST SUMMARY")
    print("="*60)
    print(f"docx_to_pdf.py:        {'✓ PASSED' if result1 else '✗ FAILED'}")
    if result2 is not None:
        print(f"simple_docx_to_pdf.py: {'✓ PASSED' if result2 else '✗ FAILED'}")
    print("="*60)
    
    # Check output files
    pdf_file = test_file.with_suffix('.pdf')
    if pdf_file.exists():
        print(f"\n✓ Output PDF created: {pdf_file}")
        print(f"  Size: {pdf_file.stat().st_size:,} bytes")
    
    if result1 or (result2 is not None and result2):
        print("\n✓ At least one converter working successfully!")
        return 0
    else:
        print("\n✗ All converters failed. Please check error messages above.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
